name: NominaSoft-CI-dev

on: [push]

jobs:
  unit-tests:
    name: Ejecución de pruebas unitarias en ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [2.2.108, 3.0.100]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Configurando .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: Corriendo pruebas unitarias
        run: |
          dotnet add package ./src/NominaSoft.Tests/NominaSoft.Tests.csproj dotnet-xunit
          dotnet test ./src/NominaSoft.Tests/NominaSoft.Tests.csproj

  build:
    name: Despliegue en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [2.2.108, 3.0.100]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    needs: unit-tests
    
    steps:
      - uses: actions/checkout@v1
      - name: Configurando .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Building
        run: dotnet build ./src
