name: NominaSoft-CI

on: 
  push:
    branches: 
      - dev

jobs:
  unit-testing:
    name: Pruebas unitarias en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1
      - name: Configurando dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Corriendo pruebas unitarias
        run: |
          dotnet restore
          dotnet add package dotnet-xunit
          dotnet test ./src/NominaSoft.Tests/NominaSoft.Tests.csproj
